### ISSUE TITLE
Can't install the package

### ISSUE THREAD

**Issue by giacomostoppa** [andreas-vester/df2img#10]
Hello,

I tried to install with pip from PyPi but it can't find the package itself:
"ERROR: Could not find a version that satisfies the requirement df2img (from versions: none)
ERROR: No matching distribution found for df2img"

I tried also from the downloaded archive df2img-0.2.0.tar.gz and this is the error i get:
"ERROR: Could not find a version that satisfies the requirement pandas<2.0.0,>=1.3.4 (from df2img) (from versions: 0.1, 0.2, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0, 0.6.0, 0.6.1, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0, 0.8.1, 0.9.0, 0.9.1,
 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.15.2, 0.16.0, 0.16.1, 0.16.2, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 0.19.2, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.21.0, 0.21.1, 0.22.0, 0.23.0, 0.
23.1, 0.23.2, 0.23.3, 0.23.4, 0.24.0, 0.24.1, 0.24.2, 0.25.0, 0.25.1, 0.25.2, 0.25.3, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5)
ERROR: No matching distribution found for pandas<2.0.0,>=1.3.4"

Can you please help me?

**Comment by andreas-vester** [comment]
It looks like ``pandas`` is causing some issues.

Can you please try ``pip install pandas --upgrade`` first. And then ``pip install df2img --upgrade``.

The package is definitely available at https://pypi.org/project/df2img/.

Let me know if this works for you.
