### ISSUE TITLE
Error: 

### ISSUE THREAD

**Issue by hbaromega** [andreas-vester/df2img#12]
I just copied and pasted the following code example from the PyPi site: 

```
import pandas as pd

import df2img

df = pd.DataFrame(
    data=dict(
        float_col=[1.4, float("NaN"), 250, 24.65],
        str_col=("string1", "string2", float("NaN"), "string4"),
    ),
    index=["row1", "row2", "row3", "row4"],
)

fig = df2img.plot_dataframe(df, fig_size=(500, 140))

df2img.save_dataframe(fig=fig, filename="plot1.png")
```
However, I'm facing the error message:

 fig = df2img.plot_dataframe(df, fig_size=(500, 140))
AttributeError: module 'df2img' has no attribute 'plot_dataframe' 

Is there an issue with the version? The installed `df2img` version in my case:  0.1.1 .

**Comment by andreas-vester** [comment]
Indeed, there are some BREAKING CHANGES in v0.2.0 (https://github.com/andreas-vester/df2img/blob/main/CHANGELOG.rst).

Just issue the following code in your command line and then you should be good to go.

``pip install df2img --upgrade``
