### ISSUE TITLE
Interactive df2img 

### ISSUE THREAD

**Issue by hbaromega** [andreas-vester/df2img#13]
Can the latest version of df2img be made as interactive as df2img 0.1.1 (like usual plots)?

**Comment by andreas-vester** [comment]
What exactly do you mean? Can you please elaborate.

**Comment by hbaromega** [comment]
It means I can get a pop-up window like what `matplotlib.pyplot.show()` does in usual plots. Then every time I won't have to open the saved image file separately.

**Comment by andreas-vester** [comment]
There's an input argument called ``show_fig`` in the ``plot_dataframe`` function. It's default is set to ``True``. It should do exactly what you're requesting.

I don't know the environment you're working in, but if no graph objects pops up, you may play around with the ``plotly_renderer`` input argument. For example, try to set it to ``browser``. More information about possible renderers can be found at plotly's website: https://plotly.com/python/renderers/

**Comment by hbaromega** [comment]
I'm using mac OS Catalina. Is it possible to install and use both versions and use either of them as per comfort?

**Comment by hbaromega** [comment]
When I set `show_fig=True`, I get this after running the code (no display):

{'image/png': 'iVBORw0KGgoAAAANSUhEUgAAAfQAAACvCAYAAAAL6CwKAAAgAElEQVR4Xu1dB5gURRN9HOnIOSMgOYhIEEQkSwaRIEgQAQm/ggoSVIKAoIBkJIgkFSRLzpKj5JxzzjnDhf97PTd3e3u7t7N3G+b2qr6Pj9vdnp6eV9P9uqqru+IEBwcHQ0QQEAQEAUFAEBAEYjQCc ...}

Could you provide a minimal example of how to set a `plotly_renderer`? Thanks.

**Comment by andreas-vester** [comment]
Again, I have no idea about your environment (IDE, Jupyter notebook, etc.). That's why I provided the link to ``plotly`` (https://plotly.com/python/renderers/).

Did you try to set ``plotly_renderer="browser"``, for example? Or what about ``plotly_renderer="svg"``?

Also, please take a look at the docs: https://df2img.readthedocs.io/en/latest/api_reference.html#
