### ISSUE TITLE
Can´t Install the package in Colab

### ISSUE THREAD

**Issue by leonardoparis** [andreas-vester/df2img#22]
Hello Andreas,

I can´t install the package in Google Colab. I´ve tried this:

!pip install pandas --upgrade 
!pip install df2img --upgrade

And the output was:

> Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (1.3.5)
> Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (1.19.5)
> Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2018.9)
> Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2.8.2)
> Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)
> **ERROR: Could not find a version that satisfies the requirement df2img (from versions: none)**
> **ERROR: No matching distribution found for df2img**

This is a feature (convert a stylized dataframe to png) that I need so much, thank you in advance if you can solve it.

Best regards.

**Comment by andreas-vester** [comment]
Can you please try to install the package in a normal virtual environment using ``pip install df2img`` and check if this is working on your end?

**Comment by leonardoparis** [comment]
I couldn´t make python work on my machine, that's why I use Colab. Sorry.

**Comment by andreas-vester** [comment]
Sorry, in that case I can't help. I am not familiar with Colab.

**Comment by leonardoparis** [comment]
Ok, thank you very much.
