### ISSUE TITLE
Please change requirement of kaleido==0.2.1 to kaleido==0.2.1.post1

### ISSUE THREAD

**Issue by giddyhup** [andreas-vester/df2img#23]
kaleido==0.2.1 cannot be installed:
```
ERROR: Could not find a version that satisfies the requirement kaleido==0.2.1 (from versions: 0.2.1.post1)
ERROR: No matching distribution found for kaleido==0.2.1
```

**Comment by andreas-vester** [comment]
The version should be available.

![grafik](https://user-images.githubusercontent.com/29901736/157752721-ddfad96b-05da-4307-a6a6-f6aab499008e.png)

**Comment by giddyhup** [comment]
Thanks for the quick response. It seems the version is not available for my architecture (arm v7), strange.
