### ISSUE TITLE
how to remove the Index column name on Data Frame image

### ISSUE THREAD

**Issue by VincentJonathanz** [andreas-vester/df2img#5]
I am confused how to remove the unwanted index column name on My Data frame image

![jadwal-mimpin-doa](https://user-images.githubusercontent.com/88643512/136327637-91919c63-ff6c-49be-8d6d-d33cdc32e1d0.png)

What i want is like this 
![jadwal-mimpin-doa-delindex](https://user-images.githubusercontent.com/88643512/136328242-a9ee7008-dbfb-4a44-873c-cad9d4f22106.png)

I've been trying to change the index in pandas data frame by using:
`df = df.rename_axis( None, axis="columns)`
but still not work.

Thank you

**Comment by VincentJonathanz** [comment]
> Do you want to completely remove the header line? This could be another feature I might look at. It could be another input argument to `df2img`, something like `header: bool = True`.

Yes i want to remove the header line, will be helpful if you add that feature

**Comment by andreas-vester** [comment]
As far as I know, ``plotly`` tables don't support the ability to hide the header row out of the box.

However, a workaround could be to set ``fill_color``, ``font_color``, and ``line_color`` to ``white``. With that, the header row still exists, but it is invisble.

I will add another input argument to control for this feature in the next release.
