### ISSUE TITLE
Lower case

### ISSUE THREAD

**Issue by as-2023** [andreas-vester/df2img#55]
Very helpful tool, thank you very much.
Is it possible to use lower case numbers or letters in the table entries? What would a corresponding string have to look like?
Thank you!

**Comment by andreas-vester** [comment]
I don't understand what you are after. Can you please give more details?

**Comment by as-2023** [comment]
Please excuse, the correct term would be subscripts, like e.g. in "CO2".

**Comment by andreas-vester** [comment]
I think this has nothing to do with ``df2img`` itself. You need to prepare the strings in your ``pd.DataFrame`` accordingly.

In Python, you can create a string containing a subscript by using Unicode characters for subscripted numbers and letters. Subscripted characters are not part of the standard ASCII character set, but they can be represented using Unicode escape sequences.

Here's an example of how to create a string with a subscript using Unicode escape sequences:

```
# Using Unicode escape sequence for subscript
subscripted_string = "H\u2082O"
print(subscripted_string)  # Output: H₂O
```

In this example, "\u2082" represents the subscript "2" (₂). The "\u" prefix indicates that the following four characters are in hexadecimal Unicode format.

Here are a few more examples for common subscript characters:

```
subscript_1 = "CO\u2082"  # CO₂
subscript_2 = "CH\u2084"  # CH₄
subscript_3 = "X\u2085"   # X₅
```

You can find the Unicode values for other subscript characters and use them in a similar manner to represent subscripts in your Python strings. Keep in mind that the rendering of these characters may depend on the font used in the output medium (e.g., terminal, text editor, etc.).

**Comment by as-2023** [comment]
This works perfectly, thank you very much for your help!
