### ISSUE TITLE
Missing install requirements in pip

### ISSUE THREAD

**Issue by feberbo** [andreas-vester/df2img#57]
Running the default tutorial on a freshly installed conda env with python 3.9 and df2img via pip raised the error:

`ValueError: Mime type rendering requires ipython but it is not installed`
and then after installing ipython
`ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed`

and then it worked.

for reference, the tutorial is:

```
import pandas as pd

import df2img

df = pd.DataFrame(
    data=dict(
        float_col=[1.4, float("NaN"), 250, 24.65],
        str_col=("string1", "string2", float("NaN"), "string4"),
    ),
    index=["row1", "row2", "row3", "row4"],
)

fig = df2img.plot_dataframe(
    df,
    col_width=[3, 2, 1],
    fig_size=(500, 140),
)

df2img.save_dataframe(fig=fig, filename="plot1.png")
```

**Comment by andreas-vester** [comment]
Thanks for pointing this out. I will incorporate it into the next version.

**Comment by andreas-vester** [comment]
This has been fixed.
