### ISSUE TITLE
Feature Request: Same column name

### ISSUE THREAD

**Issue by klq9386** [andreas-vester/df2img#6]
In the data frame did a group by but would like when the items are grouped instead of 

<table>
<tr>
<th>location</th>
<th>data</th>
</tr>
<tr>
<td>location 1</td>
<td>123</td>
</tr>
<tr>
<td>location 1</td>
<td>456</td>
</tr>
<tr>
<td>location 1</td>
<td>789</td>
</tr>
<td>location 2</td>
<td>123</td>
</tr>

</table> 

it show something like this: 

<table>
<tr>
<th>location</th>
<th>data</th>
</tr>
<tr>
<td rowspan=3>location 1</td>
<td>123</td>
</tr>
<tr>
<td>456</td>
</tr>
<tr>
<td>789</td>
</tr>
<td>location 2</td>
<td>123</td>
</tr>

</table>

**Comment by andreas-vester** [comment]
With version ``v0.2.0``, I changed the backend to ``plotly``. However, as far as I can see it, ``plotly`` tables don't support merging cells. This is a pity.
