### ISSUE TITLE
Unable to upgrade to 0.2.12

### ISSUE THREAD

**Issue by paulhybryant** [andreas-vester/df2img#61]
It returns an error like:

```
ERROR: Could not find a version that satisfies the requirement kaleido==0.1.0post1 (from df2img) (from versions: 0.0.1rc3, 0.0.1rc4, 0.0.1rc5, 0.0.1rc6, 0.0.1rc8, 0.0.1rc9, 0.0.1, 0.0.2, 0.0.3, 0.0.3.post1, 0.1.0a2, 0.1.0a3, 0.1.0, 0.2.0rc1, 0.2.0, 0.2.1)
ERROR: No matching distribution found for kaleido==0.1.0post1
```

**Comment by paulhybryant** [comment]
Thanks for fixing it, but I am still getting the same error:

pip install kaleido==0.1.0.post1 -i https://pypi.org/simple/
Looking in indexes: https://pypi.org/simple/
ERROR: Could not find a version that satisfies the requirement kaleido==0.1.0.post1 (from versions: 0.0.1rc3, 0.0.1rc4, 0.0.1rc5, 0.0.1rc6, 0.0.1rc8, 0.0.1rc9, 0.0.1, 0.0.2, 0.0.3, 0.0.3.post1, 0.1.0a2, 0.1.0a3, 0.1.0, 0.2.0rc1, 0.2.0, 0.2.1)
ERROR: No matching distribution found for kaleido==0.1.0.post1

I can find 0.1.0.post1 from pypi but installing it from pip always fails.

**Comment by paulhybryant** [comment]
From https://pypi.org/simple/kaleido/, I only see the wheel for windows. Maybe that requirement should only apply to windows as well?

**Comment by andreas-vester** [comment]
@paulhybryant I was able to replicate this issue. Using a linux box I wasn't able to install ``kaleido==0.1.0.post1``, too.
Having said that, I found that ``kaleido==0.0.3`` seems to work both under Windows and Linux. 

Let me know if this works for you.

**Comment by paulhybryant** [comment]
Sure. But if the lower kaleido version is just for the issue on windows, how about adding that condition in the requirements?

**Comment by andreas-vester** [comment]
> Sure. But if the lower kaleido version is just for the issue on windows, how about adding that condition in the requirements?

DONE

**Comment by paulhybryant** [comment]
Nice, thank you so much!

**Comment by paulhybryant** [comment]
Sorry one last thing, for != Windows, do we need to pin on such a low version (0.0.3)?
