### ISSUE TITLE
Getting error ModuleNotFoundError: No module named 'df2img'

### ISSUE THREAD

**Issue by shashikulk** [andreas-vester/df2img#64]
I am trying to use df2img, but getting the said error at
```
import df2img
```
I am using Windows 11 laptop. I have upgraded pandas and plotly to latest versions, and have upgraded kaleido to v0.1.0.post1. After that I installed df2img v0.2.16. But still getting this error.

Please help with a solution.

**Comment by andreas-vester** [comment]
@shashikulk 
@walternat1ve
Can you please install ``df2img==0.2.18``? Let me know if this is working on both Windows and Linux.

**Comment by andreas-vester** [comment]
> I observed that when I upgraded `df2img` to `0.2.18`, the version of `kaleido` changed from `0.1.0.post1` back to `0.0.3`. Is this an expected behavior while installing/upgrading `df2img` ?

Yes, this is to be expected. ``kaleido==0.0.3`` seemst to be the only version that is compatible with the latest ``plotly`` version for both Windows and Linux.

There are several open issues regarding ``kaleido``.  
https://github.com/plotly/Kaleido/issues/134
https://github.com/plotly/plotly.py/issues/3744
https://github.com/plotly/plotly.py/issues/4401

**Comment by shashikulk** [comment]
This issue/bug is resolved for Windows. If it is tested for Linux and working fine, it can be closed. 

Thanks @andreas-vester for quickly resolving it! I do have a query about using Devanagari fonts in ```df2img.plot_dataframe()``, will create a separate issue for the same.
