### ISSUE TITLE
Selected cell formatting

### ISSUE THREAD

**Issue by trjcaz** [andreas-vester/df2img#65]
Hi, would it be possible to implement the option to give format to particular cells? 
As an example the situation I am having is that I want to highlight or bold the numbers in the cells that have the highest value in their column. The only formatting options I have seen apply to all cells.
I have tried passing a dataframe with color values to the font_color parameter of tbl_cells but it reacts randomly (I'm not sure if this should be reported as a bug).

Thank you!

**Comment by andreas-vester** [comment]
Sorry, I don't think it's possible to format individual cells.
