### ISSUE TITLE
Kalideo Package Issue

### ISSUE THREAD

**Issue by jaskirat8** [andreas-vester/df2img#66]
The dependency "kaleido==0.0.3" is not available for macos and causing "df2img" library to be unusable. Should we consider bumping it ?

<img width="1231" alt="image" src="https://github.com/andreas-vester/df2img/assets/19311617/e405cacf-08ea-45b4-8ade-65ab38dbe2ed">

**Comment by andreas-vester** [comment]
@jaskirat8 
There are issues with ``kaleido`` for some time now. What I figured out is that the latest ``kaleido`` version is not compatible with ``plotly`` (the charting backend used in ``df2img``) anymore.

For Windows machines, ``kaleido==0.1.0.post1`` is working. For Linux, you need to downgrade to ``kaleido==0.0.3``. That is, I previously put the lowest version into ``pyproject.toml``.

Now I changed the required ``kaleido`` version in the ``pyproject.toml`` file depending on the operating system. As I don't have any MacOS at hand to fully test it, I am wondering if you can clone the repo to your local machine and check out the new branch ``update_kaleido``? If all ``pytest`` unit tests pass, everything will be fine and I'll merge it into ``main``.
